[package]
name = "burger_production"
version = "0.1.0"
edition = "2021"

[dependencies]
rsim = { path = "../.." }
rand = "0.8"
rand_distr = "0.4"
uuid = { version = "1.0", features = ["v4"] }
log = "0.4.27"
env_logger = "0.11.8"

[[bin]]
name = "burger_production"
path = "main.rs"
